import sys

def beautify_buttons(filepath):
    with open(filepath, "r", encoding="utf-8") as f:
        content = f.read()
    
    # 1. Update the CSS for the buttons
    old_css = """.admin-fest-status-btn {
    border: none;
    border-radius: 6px;
    padding: 4px 10px;
    font-size: 0.78rem;
    font-weight: 600;
    cursor: pointer;
    transition: opacity 0.15s ease;
  }"""
    
    new_css = """.admin-fest-status-btn {
    border: 1px solid #e2e8f0;
    background: #ffffff;
    color: #475569;
    border-radius: 6px;
    padding: 6px 12px;
    font-size: 0.8rem;
    font-weight: 600;
    cursor: pointer;
    transition: all 0.2s ease;
    display: inline-flex;
    align-items: center;
    gap: 6px;
    box-shadow: 0 1px 2px rgba(0,0,0,0.05);
  }
  .admin-fest-status-btn:hover:not(:disabled) {
    background: #f8fafc;
    border-color: #cbd5e1;
    color: #0f172a;
    box-shadow: 0 2px 4px rgba(0,0,0,0.05);
  }
  .admin-fest-status-btn:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }
  .admin-fest-status-btn.danger {
    color: #ef4444;
    border-color: #fca5a5;
    background: #fef2f2;
    padding: 6px 8px; /* Slightly less padding for just the icon */
  }
  .admin-fest-status-btn.danger:hover:not(:disabled) {
    background: #fee2e2;
    border-color: #f87171;
    color: #b91c1c;
  }"""
    
    if "display: inline-flex;" not in content:
        content = content.replace(old_css, new_css)
        
    # 2. Update the buttons in renderOrdersTable
    old_buttons = """<button class="admin-fest-status-btn" onclick="viewOrderDetails(${order.id})" title="Details anzeigen" style="margin-right: 5px;">👁️ Öffnen</button>
          <button class="admin-fest-status-btn" onclick="openReturnModal(${order.id})" title="Retoure verbuchen" ${order.status === 'abgeschlossen' ? 'disabled' : ''}>🔙 Retoure</button>
          <button class="admin-fest-status-btn" style="color: #EF4444; border-color: #EF4444;" onclick="deleteOrder(${order.id})" title="Löschen">🗑️</button>"""
          
    new_buttons = """<button class="admin-fest-status-btn" onclick="viewOrderDetails(${order.id})" title="Details anzeigen">
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M2 12s3-7 10-7 10 7 10 7-3 7-10 7-10-7-10-7Z"/><circle cx="12" cy="12" r="3"/></svg>
            Öffnen
          </button>
          <button class="admin-fest-status-btn" onclick="openReturnModal(${order.id})" title="Retoure verbuchen" ${order.status === 'abgeschlossen' ? 'disabled' : ''}>
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/><polyline points="9 22 9 12 15 12 15 22"/></svg>
            Retoure
          </button>
          <button class="admin-fest-status-btn danger" onclick="deleteOrder(${order.id})" title="Löschen">
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M3 6h18"/><path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6"/><path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2"/></svg>
          </button>"""
          
    if "<svg" not in old_buttons: # simple check
        content = content.replace(old_buttons, new_buttons)
    
    # 3. Fix the "PDF erstellen" button (it says 📄 PDF erstellen in index.html in the HTML body or generated by JS)
    # Let's search for "📄 PDF erstellen" and replace with "PDF erstellen"
    content = content.replace("📄 PDF erstellen", "PDF erstellen")
    content = content.replace("📄 Zusammenstellen", "Zusammenstellen")

    # Also fix the title of the orders table "📋 Bestellungen & Fest-Retouren"
    content = content.replace("📋 Bestellungen", "Bestellungen")

    with open(filepath, "w", encoding="utf-8") as f:
        f.write(content)

beautify_buttons("index.html")
beautify_buttons("getraenke-bestelltool.html")
